# Generated by Django 4.2.5 on 2023-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('roomtype', models.CharField(choices=[('B', 'Baan Tao'), ('C', 'Café 88'), ('T', 'The Terrace Bar'), ('W', 'The Waterfall Lounge'), ('R', 'In-Room Dining Services')], max_length=1)),
            ],
        ),
    ]
